apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: color
  namespace: default
spec:
  encryptedData:
    COLOR_ENV: AgBhTDZZ9TzajG04FpiyDdFAU2V6D2I5jYpZK0Ax9GvDIjvLq4Suie9EzLf1C69kx6nxLBRT5UxyR/zOcfDU+z0nETC4flfVfnsvVnIU0+E3XPn5ZdUvhxY3vA2xgTwEuJY/lOdn/i62AyV3EREo/lLfcb7/qn+QqEJq1cBsTHrC8kz8DjcOxsWPo3sebYso4x4a6EWy+OxqsRCgwqs5K0+2KpZA/SuPtLFJozBx3Jo8GlBuIV82cj/j0HfH23NfWS/1c3t68jR8638F8gDrIYiRzJ5FxYhaLA8y2YtkBNDSYZ/PaE2O2ueOxjCMcRAWxrDeEDCHD2sQP/6KJbVbpNqlj7CrV8rYon3pHtjxWqooUT01jFUxQ8GDHC0OzW3ufljqa7TjhI2v4OA/0M4M0gV3BZnfOj7/Fpj+K5k+0Sk9/f3ueQjDd6tlKgKDdPegr3HnL0lA68qyY5Xgj6Qi1JIS1oaQykOoq7BtO2nk2b3Qy+F1VOnuxFPJksqtNyoB4lUD/mlHXcjhc6+PIliFQLz5j2gMVFi3Pqtg+Z9XfJ7PPXXVMLFbtFruWxlHK/Id960U1PCogT2VCQQfYPSzsROSo6naEm9gf0iaUZcM3to3tFMccMf4SRgOO17psPmoQTYN3WO8VykGyhLaaRmuvSybfxRxVz84hHvwZFmSiw8WIaDo/GHltRT0lUOxoupBGOlhDN9a
  template:
    metadata:
      creationTimestamp: null
      name: color
      namespace: default

